name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Укажите ветку, которая запускает деплой

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Проверяем код из репозитория
    - name: Checkout code
      uses: actions/checkout@v3

    # Шаг 2: Устанавливаем Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Шаг 3: Устанавливаем зависимости и билдим проект
    - name: Install dependencies and build
      run: |
        npm install
        npm run build
        npm run export

    # Шаг 4: Публикуем проект на GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
